[build]
  publish = "public"
  command = "gatsby build"
  
[build.environment]
  NODE_VERSION = "20.10.0"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"

[[plugins]]
  package = "@netlify/plugin-gatsby"
