name = "cobaltwebtech"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-06-25"
compatibility_flags = [ "nodejs_compat" ]
tail_consumers = [{service = "cobaltwebtech-sentry"}]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
TURNSTILE_PUBLIC_KEY = "0x4AAAAAAAAtFFFWPGStA0h_"
UMAMI_ID = "758cbc64-fa17-4c53-98ad-63af8eafeb3b"

[[kv_namespaces]]
binding = "COBALTWEBTECH_USER_BLOCK_DATA"
id = "bffb36f2981a48ab90f807b787231bb5"
preview_id = "73147734785f43d9b3579ef9b991cf32"

# Cloudflare Rate Limiting API binding
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001" 
simple = { limit = 100, period = 60 }  # 100 requests per minute per IP