name = "cobaltwebtech"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-14"
compatibility_flags = [ "nodejs_compat" ]
tail_consumers = [{service = "cobaltwebtech-sentry"}]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
UMAMI_ID = "758cbc64-fa17-4c53-98ad-63af8eafeb3b"
TURNSTILE_PUBLIC_KEY = "0x4AAAAAAAAtFFFWPGStA0h_"