name = "cobaltwebtech"
main = "./dist/_worker.js/index.js"
compatibility_date = "2025-05-14"
compatibility_flags = [ "nodejs_compat" ]

[assets]
binding = "ASSETS"
directory = "./dist"

[observability]
enabled = true

[vars]
UMAMI_ID = "758cbc64-fa17-4c53-98ad-63af8eafeb3b"
TURNSTILE_PUBLIC_KEY = "0x4AAAAAAAAtFFFWPGStA0h_"
SENTRY_URL= "https://1cb4221444916db69fb6830adcab2f20@o4508880993058816.ingest.us.sentry.io/4508881028907008"